name: docs_QuantumGraphColoring
channels:
  - conda-forge
  - defaults
dependencies:
  # Base depends
  - python
  - pip

  # Project depends
  - matplotlib
  - numpy
  - networkx
  - qiskit
  - qiskit-aer
  

  # Sphinx extensions
  - pydata-sphinx-theme
  - sphinx-design
  - sphinx-copybutton

  # Pip-only installs
  - pip:
      - -e ../
